#!/usr/bin/env bash
# exit 0 when used
# exit 1 when not used
socket=$1

[[ -z ${socket} ]]        && exit 1
[[ ! -S ${socket} ]]      && exit 1

pids="$(pidof nvim | awk '{ print $1 }')"
for pid in ${pids}; do
  lsof -p ${pid} | grep -c ${socket} &> /dev/null && exit 0
done
exit 1
