iabbrev neccesery    necessary
iabbrev neccisty     necessity
iabbrev nessacerry   necessary
iabbrev nessacery    necessary
iabbrev nessicerry   necessary
iabbrev reprosent    represent
iabbrev seperate     separate
iabbrev slef         self
iabbrev teh          the
